defaults:
  - trainer: default.yaml
  - datamodule: patches.yaml
  - model: autoencoder.yaml
  - logger: wandb.yaml
  - hydra: default.yaml
  - callbacks: default.yaml
  - _self_

work_dir: ${hydra:runtime.cwd}
seed: null