visualize_filters:
  _target_: src.callbacks.VisualizeFilters
  patch_width: ${datamodule.patch_width}
  patch_height: ${datamodule.patch_height}
  nrow: 20
  padding: 2

dict_incoherence:
  _target_: src.callbacks.DictionaryIncoherence

save_weights:
  _target_: src.callbacks.SaveWeights
  save_last_epoch_only: True
  save_dirs:
    top_dir: ${work_dir}/saved_weights
    data_dir: ${callbacks.distance.fname}_k=${datamodule.k}_noise=${datamodule.noise}
    arch_dir: fc_width=${model.width}_act=${model.activation.name}_tied=${model.tied_weights}
    exp_dir: ''

weight_norm:
  _target_: src.callbacks.WeightNorm

distance:
  _target_: src.callbacks.DistanceToReference
  save_dir: ${datamodule.save_dir}
  fname: gabor_${datamodule.patch_width}x${datamodule.patch_height}_m=${datamodule.m}_L=${datamodule.L}_inc=${datamodule.inc_bound}_seed=${seed}
  param_key: W
  reco_thresh: 0.7
  