visualize_filters:
  _target_: src.callbacks.VisualizeFilters
  patch_width: ${datamodule.patch_width}
  patch_height: ${datamodule.patch_height}
  nrow: 20
  padding: 2

save_weights:
  _target_: src.callbacks.SaveWeights
  save_dirs:
    top_dir: ${work_dir}/saved_weights
    data_dir: patches_${datamodule.patch_width}x${datamodule.patch_height}_raw=${datamodule.use_rawimage}_ntrain=${datamodule.n_train}
    arch_dir: fc_width=${model.width}_act=${model.activation.name}_tied=${model.tied_weights}
    exp_dir: finetune_delta=${model.initializer.delta}
  batch_size: ${datamodule.batch_size}

distance:
  _target_: src.callbacks.DistanceToReference
  save_dir: ${work_dir}/saved_weights/patches_12x12_raw=False_ntrain=500000/fc_width=200_act=Sigmoid_tied=True/good_filters
  fname: adam_lr=0.01_bs=500_sigma=0.5_epoch=24_seed=1
  ext: .pt